[profile.default]
src = 'src'                                                   # the source directory
test = 'test'                                                 # the test directory
out = 'out'                                                   # the output directory (for artifacts)
libs = ['lib']                                                # a list of library directories
#solc_version = '0.8.13'                                      # override for the solc version (setting this ignores `auto_detect_solc`)
optimizer = true                                              # enable or disable the solc optimizer
optimizer_runs = 200                                          # the number of optimizer runs

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
